# openapi: 3.0.0
# info:
#   title: Epic Movie Quotes API
#   description: Here goes description
#   version: 1.0.0

# servers:
#   - url: http://localhost:8000/api
#     description: local server
#   - url: http://producation.app/api
#     description: production server

# paths:
#   /signup:
#     post:
#       summary: sign up a user.
#       responses:
#         "200":
#           description: A JSON array of user names
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   type: string

openapi: 3.0.0
info:
  title: Topelectro API
  description: Here goes description
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://production-example:8000/api
    description: production server

paths:
  /signup:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1signup"
  /signin:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1signin"
  /signout:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1signout"

  # /products:
  #   $ref: "./_swagger/paths/products.yaml#/paths/~1products"
  # /products/{id}:
  #   $ref: "./_swagger/paths/products.yaml#/paths/~1products~1{id}"

  # /categories:
  # $ref: "./_swagger/paths/categories.yaml#/paths/~1categories"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      allOf:
        - $ref: "./_swagger/schemas/user.yaml#/components/schemas/User"
    Movie:
      allOf:
        - $ref: "./_swagger/schemas/movie.yaml#/components/schemas/Movie"
