# openapi: 3.0.0
# info:
#   title: Epic Movie Quotes API
#   description: Here goes description
#   version: 1.0.0

# servers:
#   - url: http://localhost:8000/api
#     description: local server
#   - url: http://producation.app/api
#     description: production server

# paths:
#   /signup:
#     post:
#       summary: sign up a user.
#       responses:
#         "200":
#           description: A JSON array of user names
#           content:
#             application/json:
#               schema:
#                 type: array
#                 items:
#                   type: string

openapi: 3.0.0
info:
  title: Epic Movie Quotes API
  description: Here goes description
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://production-example:8000/api
    description: production server

paths:
  /signup:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1signup"
  /signin:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1signin"
  /signout:
    $ref: "./_swagger/paths/auth.yaml#/paths/~1signout"
  /email/verify/{id}/{hash}:
    $ref: "./_swagger/paths/email.yaml#/paths/~1email~1verify~1{id}~1{hash}"
  /forgot-password:
    $ref: "./_swagger/paths/forgotPassword.yaml#/paths/~1forgot-password"
  /reset-password:
    $ref: "./_swagger/paths/forgotPassword.yaml#/paths/~1reset-password"
  /email:
    $ref: "./_swagger/paths/profile.yaml#/paths/~1email"
  /delete-email:
    $ref: "./_swagger/paths/profile.yaml#/paths/~1delete-email"
  /make-primary-email:
    $ref: "./_swagger/paths/profile.yaml#/paths/~1make-primary-email"
  /user:
    $ref: "./_swagger/paths/profile.yaml#/paths/~1user"
  /user-update:
    $ref: "./_swagger/paths/profile.yaml#/paths/~1user-update"
  /movies:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1my-movies"
  /movies/{id}:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movies~1{id}"
  /movies/{id}/quotes:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movies~1{id}~1quotes"
  /quote:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote"
  /quote/{id}:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{id}"
  /quote/{id}?_method=patch:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{id}?_method=patch"
  /comment:
    $ref: "./_swagger/paths/comment.yaml#/paths/~1comment"
  /like:
    $ref: "./_swagger/paths/like.yaml#/paths/~1like"

  # /products:
  #   $ref: "./_swagger/paths/products.yaml#/paths/~1products"
  # /products/{id}:
  #   $ref: "./_swagger/paths/products.yaml#/paths/~1products~1{id}"

  # /categories:
  # $ref: "./_swagger/paths/categories.yaml#/paths/~1categories"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      allOf:
        - $ref: "./_swagger/schemas/user.yaml#/components/schemas/User"
    Movie:
      allOf:
        - $ref: "./_swagger/schemas/movie.yaml#/components/schemas/Movie"
